# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "ECEn 626: Exploring SDRs"
class_name: Computer Networks
class_number: ECEn 626
email: lundrigan@byu.edu
description: >-
  Class website for BYU's ECEn 626: Exploring Software-defined Radios
host: localhost
baseurl: "/626" # the subpath of your site, e.g. /blog
url: "https://ecenetworking.byu.edu" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-target-blank
  
# Turn on the button to allow students to submit PRs to change a page
suggest_edits:
  enable: true
  link: https://github.com/byu-cpe/ecen626_website/blob/main

# Set the color theme of the page
colors:
  text_color: "#111"
  background_color: "#fdfdfd"
  brand_color: "#ed3d96"
  secondary_color: "#c3e6ef"
  text_selection_color: "#ffde16"
  sidebar_hover_color: "#faa220"

# Set the fonts
fonts:
  base: "'neue-haas-unica', 'Helvetica Neue', Helvetica, Arial, sans-serif"
  header: "omnium, sans-serif"
  # If you want a more traditional font, consider using this instead:
  # header: "'Ubuntu', sans-serif"

collections:
  labs:
    output: true
    permalink: /:collection/:title/
    sort_by: number
  activities:
    output: true
    permalink: /:collection/:name/
    sort_by: number
  pages:
    output: true
    permalink: /:name/
    order:
      - overview.md
      - resources.md
      - coding_standard.md
      - lab_setup.md
      - craftsmanship.md
      - ta_hours.md
      - schedule.md

defaults:
  - scope:
      path: ""
      type: "labs"
    values:
      layout: "lab"
      toc: true
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - icon.ai
  - Dockerfile
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
